### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by giacomorebecchi** [giacomorebecchi/food-pricing#45]
Got the following traceback:
```
Complete traceback: Traceback (most recent call last):
  File "/home/ubuntu/Documents/thesis/food-pricing/src/models/base_model.py", line 279, in _unfreeze_module
    self.optimizers().add_param_group(
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/torch/optim/optimizer.py", line 316, in add_param_group
    raise ValueError("some parameters appear in more than one parameter group")
ValueError: some parameters appear in more than one parameter group

2022-08-24 11:23:09,591 INFO train main Finished fitting model FPCBOWResNet152ConcatBaselineModel.
2022-08-24 11:24:29,692 INFO train main Finished submitting predictions for model FPCBOWResNet152ConcatBaselineModel.
2022-08-24 11:24:29,692 INFO train main Released memory occupied from model FPCBOWResNet152ConcatBaselineModel.
2022-08-24 11:24:29,692 INFO train main Creating instance of model FPBERTResNet152ConcatModel.
2022-08-24 11:24:29,693 INFO storage get_local_models_path Path /home/ubuntu/Documents/thesis/food-pricing/models/FPBERTResNet152ConcatModel did not exist. Created it.
2022-08-24 11:24:32,737 INFO pretrained_bert __init__ Adding a Fully Connected Layer to pass from 768 to 512 features.
2022-08-24 11:24:38,290 INFO pretrained_resnet __init__ Substituting the last ResNet152 layer with a trainable Fully Connected Layer to pass from 2048 to 512 features.
2022-08-24 11:24:38,321 INFO train main Starting to fit model FPBERTResNet152ConcatModel.
2022-08-24 11:34:24,379 INFO pretrained_resnet unfreeze_encoder Encoder model PreTrainedResNet152 started fine-tuning
2022-08-24 11:55:47,511 INFO pretrained_bert unfreeze_encoder Encoder model PreTrainedBERT started fine-tuning
2022-08-24 11:55:47,515 INFO base_model _unfreeze_module Attempt to add parameters of PreTrainedResNet152 to optimizer failed.
Complete traceback: Traceback (most recent call last):
  File "/home/ubuntu/Documents/thesis/food-pricing/src/models/base_model.py", line 279, in _unfreeze_module
    self.optimizers().add_param_group(
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/torch/optim/optimizer.py", line 316, in add_param_group
    raise ValueError("some parameters appear in more than one parameter group")
ValueError: some parameters appear in more than one parameter group

2022-08-24 12:20:26,092 ERROR train <module> Traceback (most recent call last):
  File "/home/ubuntu/Documents/thesis/food-pricing/src/models/train.py", line 81, in <module>
    main()
  File "/home/ubuntu/Documents/thesis/food-pricing/src/models/train.py", line 65, in main
    model.fit()
  File "/home/ubuntu/Documents/thesis/food-pricing/src/models/base_model.py", line 239, in fit
    self.trainer.fit(self, datamodule=self.data)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 205, in run
    self.on_advance_end()
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 294, in on_advance_end
    self.trainer._call_callback_hooks("on_train_epoch_end")
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1636, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 308, in on_train_epoch_end
    self._save_topk_checkpoint(trainer, monitor_candidates)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 379, in _save_topk_checkpoint
    self._save_monitor_checkpoint(trainer, monitor_candidates)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 651, in _save_monitor_checkpoint
    self._update_best_and_save(current, trainer, monitor_candidates)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 702, in _update_best_and_save
    self._save_checkpoint(trainer, filepath)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 384, in _save_checkpoint
    trainer.save_checkpoint(filepath, self.save_weights_only)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 2467, in save_checkpoint
    self._checkpoint_connector.save_checkpoint(filepath, weights_only=weights_only, storage_options=storage_options)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 445, in save_checkpoint
    self.trainer.strategy.save_checkpoint(_checkpoint, filepath, storage_options=storage_options)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 418, in save_checkpoint
    self.checkpoint_io.save_checkpoint(checkpoint, filepath, storage_options=storage_options)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/plugins/io/torch_plugin.py", line 54, in save_checkpoint
    atomic_save(checkpoint, path)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/utilities/cloud_io.py", line 67, in atomic_save
    torch.save(checkpoint, bytesbuffer)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/torch/serialization.py", line 604, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 100067) is killed by signal: Killed. 
```

**Comment by giacomorebecchi** [comment]
The debug of this looks long and cumbersome. Tentative (temporary) solution is setting `loader_workers` hparam to 0.

**Comment by giacomorebecchi** [comment]
See this [Pytorch issue](https://github.com/pytorch/pytorch/issues/8976) for details
