### ISSUE TITLE
LR Scheduler fails

### ISSUE THREAD

**Issue by giacomorebecchi** [giacomorebecchi/food-pricing#49]
Complete traceback:
```
2022-08-25 00:31:06,725 root CRITICAL train main Traceback (most recent call last):
  File "/home/ubuntu/Documents/thesis/food-pricing/src/models/train.py", line 66, in main
    model.fit()
  File "/home/ubuntu/Documents/thesis/food-pricing/src/models/base_model.py", line 239, in fit
    self.trainer.fit(self, datamodule=self.data)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 205, in run
    self.on_advance_end()
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 303, in on_advance_end
    self.epoch_loop.update_lr_schedulers("epoch", update_plateau_schedulers=True)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 432, in update_lr_schedulers
    self._update_learning_rates(
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 493, in _update_learning_rates
    self.trainer._call_lightning_module_hook(
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1562, in lr_scheduler_step
    scheduler.step(metric)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 939, in step
    self._reduce_lr(epoch)
  File "/home/ubuntu/mambaforge/envs/food-pricing/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 948, in _reduce_lr
    new_lr = max(old_lr * self.factor, self.min_lrs[i])
IndexError: list index out of range
```

**Comment by giacomorebecchi** [comment]
It could be nice to open an issue in Pytorch Lightning to signal this issue and offer a PR to handle this situation.
